FROM jupyter/base-notebook 

USER root
# Copy in files to identify and trust host certs/CAs
RUN mkdir -p /opt/rucio/etc /etc/vomses /etc/pki/tls/certs
COPY skatelescope.eu* /etc/vomses/
COPY voms-escape.cloud.cnaf.infn.it.vomses /etc/vomses/
COPY voms-escape.cloud.cnaf.infn.it.lsc /etc/grid-security/vomsdir/
COPY rucio.cfg.*.j2 / 
COPY EGI-trustanchors /
COPY initialise-user-auth /home/$NB_USER 

RUN apt-get update && apt-get install -y gnupg2 vim
RUN wget -q -O - https://dist.eugridpma.info/distribution/igtf/current/GPG-KEY-EUGridPMA-RPM-3 | apt-key add -
RUN cat /EGI-trustanchors >> /etc/apt/sources.list
RUN apt-get update && apt-get install -y ca-certificates ca-policy-egi-core gfal2 voms-clients-java
RUN ln -s /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt

RUN pip install --pre rucio-clients==1.21.12 
RUN pip install jinja2 j2cli pyyaml

RUN fix-permissions /home/$NB_USER && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /opt/rucio/etc && \
    fix-permissions /etc/vomses/
USER $NB_UID
