#!/bin/bash

# This assumes your grid cert's pem files (usercert.pem and userkey.pem) are in the PWD

mkdir -p /opt/rucio/etc/
chmod 0400 userkey.pem
cp -r user* /opt/rucio/etc/
# Add your rucio account name below or pass as an argument to this script
export RUCIO_CFG_ACCOUNT=$1
# Update template file to be used if you want to point to different Rucio instance
j2 /rucio.cfg.escape.j2 > /opt/rucio/etc/rucio.cfg
