#!/bin/bash 

if [ "$DOCKER_TAG" == "latest" ]; then
  docker build . -f $DOCKERFILE_PATH --tag $IMAGE_NAME
elif [ "$DOCKER_TAG" == "py3" ]; then
  docker build . -f $DOCKERFILE_PATH --build-arg BASEIMAGE=rucio/rucio-clients:release-1.24.1.post1 --tag $IMAGE_NAME
fi
